FROM mariadb:11.3.2

LABEL maintainer="andika"
LABEL image="andika/pdns-mariadb"
LABEL version="v1"

ENV MARIADB_ROOT_PASSWORD=rootpass
ENV MARIADB_DATABASE=powerdns
ENV MARIADB_USER=pdns
ENV MARIADB_PASSWORD=pdnspass

EXPOSE 3306
